edition = "2024"
max_width = 100
use_field_init_shorthand = true
use_try_shorthand = true
reorder_imports = true
reorder_modules = true
newline_style = "Unix"

# nightly (unused, but ideal)
group_imports = "StdExternalCrate" # https://github.com/rust-lang/rustfmt/issues/5083
